spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate :
        format_sql : true


project:
   poster: poster/


base:
  url: "http://localhost:8080"


  spring:
    jpa:
      hibernate:
        ddl-auto: create